// Cara launch action-parity registry.
//
// The launch promise: **anything a user can do on the web, Cara can do over
// SMS.** This module is the single, machine-checkable map of every
// launch-critical client / caregiver / admin action to the Cara MCP tool (or
// handler) that performs it. context/capability-map.md is the human-readable
// mirror; THIS file is the source of truth.
//
// toolCapabilities.test.ts enforces the invariants:
//   • shipped rows point at a real MCP_TOOLS tool
//   • blocker rows carry tool:null (a gap must not claim a shipped tool)
//   • every collection is "n/a" or a key in CONTRACT_COLLECTIONS
//   • shipped caregiver-actor tools are reachable by the caregiver prompt filter
//
// Status meanings:
//   shipped   — the tool exists in MCP_TOOLS today and is wired to the web-read
//               Firestore shape.
//   blocker   — launch-critical parity gap. tool MUST be null. The intended tool
//               name lives in `action`. U2 (caregiver) and U3 (admin) flip these
//               to shipped.
//   non-goal  — explicitly out of scope per the plan's Scope Boundaries
//               (medical advice, raw card capture, bookable-without-Checkr).

export interface LaunchAction {
  /** Stable kebab id, e.g. "client-book-caregiver". Unique across the registry. */
  id: string;
  actor: "client" | "caregiver" | "admin" | "family";
  /** Human description of the action (for blocker rows, name the intended tool here). */
  action: string;
  /** Component/page that performs this on the web. */
  webSurface: string;
  /** Primary Firestore collection. "n/a" or a key in CONTRACT_COLLECTIONS. */
  collection: string;
  /** Cara MCP tool name (or handler). null only when status is "blocker" or "non-goal". */
  tool: string | null;
  /**
   * Which prompt/tool-filter actor should expose this tool:
   *   "client" | "caregiver" | "admin" — actor-specific prompt surface.
   *   "any"  — cross-cutting tool exposed regardless of actor (core reads,
   *            messaging, support, journal that both sides touch).
   *   null   — no tool is exposed yet (blocker / non-goal rows).
   */
  promptActor: "client" | "caregiver" | "admin" | "any" | null;
  status: "shipped" | "blocker" | "non-goal";
  /**
   * How the action is exposed:
   *   "mcp"      — a Cara MCP tool in MCP_TOOLS (default when undefined).
   *   "callable" — a Firebase https.onCall callable exported from
   *                functions/src/index.ts (admin execution actions, U3). These
   *                are NOT exposed as client/caregiver MCP tools; `tool` names
   *                the callable export.
   */
  surface?: "mcp" | "callable";
  /** Optional clarification — why blocked, which unit ships it, scope rationale. */
  notes?: string;
}

export const LAUNCH_ACTION_PARITY: readonly LaunchAction[] = [
  // ── Client (R1) ───────────────────────────────────────────────────────────
  {
    id: "client-find-caregiver",
    actor: "client",
    action: "Search/match caregivers and request replacements",
    webSurface: "components/client/FindCaregivers.tsx",
    collection: "caregivers",
    tool: "find_replacement_caregivers",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-book-caregiver",
    actor: "client",
    action: "Book a caregiver (creates pending_caregiver_confirmation appointment)",
    webSurface: "components/BookingModal.tsx",
    collection: "appointments",
    tool: "request_booking",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-reschedule-appointment",
    actor: "client",
    action: "Reschedule an existing appointment",
    webSurface: "components/client/AppointmentsPage.tsx",
    collection: "appointments",
    tool: "reschedule_appointment",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-cancel-appointment",
    actor: "client",
    action: "Cancel an appointment",
    webSurface: "components/client/AppointmentsPage.tsx",
    collection: "appointments",
    tool: "cancel_appointment",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-update-care-plan",
    actor: "client",
    action: "Update the senior's care plan",
    webSurface: "components/client/CarePlan.tsx",
    collection: "carePlans",
    tool: "update_care_plan",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-add-family-member",
    actor: "client",
    action: "Add a member to the family group",
    webSurface: "components/client/CareTeam.tsx",
    collection: "family_groups",
    tool: "add_family_member",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-remove-family-member",
    actor: "client",
    action: "Remove a member from the family group",
    webSurface: "components/client/CareTeam.tsx",
    collection: "family_groups",
    tool: "remove_family_member",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-read-care-journal",
    actor: "client",
    action: "Read the care journal / visit updates",
    webSurface: "components/client/CareJournalFeed.tsx",
    collection: "care_journal",
    tool: "get_care_journal_client",
    promptActor: "any",
    status: "shipped",
  },
  {
    id: "client-comment-care-journal",
    actor: "client",
    action: "Comment on / like a care journal entry",
    webSurface: "components/client/CareJournalFeed.tsx",
    collection: "care_journal",
    tool: "comment_on_journal_entry",
    promptActor: "any",
    status: "shipped",
  },
  {
    id: "client-message-caregiver",
    actor: "client",
    action: "Message a caregiver",
    webSurface: "components/shared/MessagingPanel.tsx",
    collection: "threads",
    tool: "send_caregiver_message",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-create-support-ticket",
    actor: "client",
    action: "Open a support ticket",
    webSurface: "components/shared/SupportWidget.tsx",
    collection: "support_tickets",
    tool: "create_support_ticket",
    promptActor: "any",
    status: "shipped",
  },
  {
    id: "client-update-payment-method",
    actor: "client",
    action: "Get a Stripe payment-method update link",
    webSurface: "components/client/BillingPage.tsx",
    collection: "n/a",
    tool: "get_payment_update_link",
    promptActor: "any",
    status: "shipped",
    notes: "Raw card details are never captured in chat; Cara only hands off a Stripe-hosted link.",
  },
  {
    id: "client-view-invoices",
    actor: "client",
    action: "View invoice history and details",
    webSurface: "components/client/BillingPage.tsx",
    collection: "n/a",
    tool: "get_invoice_history",
    promptActor: "client",
    status: "shipped",
    notes: "Invoices live in Stripe + billing summaries, not a registered Firestore contract collection.",
  },
  {
    id: "client-view-timesheets",
    actor: "client",
    action: "View pending timesheets awaiting approval",
    webSurface: "components/client/TimesheetsPage.tsx",
    collection: "shiftHours",
    tool: "get_pending_timesheets",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-approve-timesheet",
    actor: "client",
    action: "Approve/reject submitted shift hours",
    webSurface: "components/client/TimesheetsPage.tsx",
    collection: "shiftHours",
    tool: "review_shift_hours",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-request-refund",
    actor: "client",
    action: "Request a refund (creates admin-visible state)",
    webSurface: "components/client/BillingPage.tsx",
    collection: "admin_alerts",
    tool: "create_refund_request",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-create-reminder",
    actor: "client",
    action: "Create a care reminder",
    webSurface: "components/client/RemindersPage.tsx",
    collection: "n/a",
    tool: "create_reminder",
    promptActor: "client",
    status: "shipped",
    notes: "Reminders are scheduled triggers, not a registered contract collection.",
  },
  {
    id: "client-submit-review",
    actor: "client",
    action: "Submit a caregiver review",
    webSurface: "components/client/ReviewModal.tsx",
    collection: "caregivers",
    tool: "submit_review",
    promptActor: "client",
    status: "shipped",
  },

  // ── Caregiver (R2) ────────────────────────────────────────────────────────
  {
    id: "caregiver-update-profile",
    actor: "caregiver",
    action: "Update caregiver profile (rate/skills/bio)",
    webSurface: "components/caregiver/CaregiverProfilePage.tsx",
    collection: "caregivers",
    tool: "update_caregiver_profile",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-update-availability",
    actor: "caregiver",
    action: "Update availability",
    webSurface: "components/caregiver/CaregiverCalendar.tsx",
    collection: "caregivers",
    tool: "update_caregiver_availability",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-browse-jobs",
    actor: "caregiver",
    action: "Browse the job board",
    webSurface: "components/caregiver/JobBoard.tsx",
    collection: "job_posts",
    tool: "browse_job_board",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-apply-to-job",
    actor: "caregiver",
    action: "Apply to a job post",
    webSurface: "components/caregiver/JobBoard.tsx",
    collection: "job_posts",
    tool: "apply_to_job",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-withdraw-application",
    actor: "caregiver",
    action: "Withdraw a job application",
    webSurface: "components/caregiver/JobBoard.tsx",
    collection: "job_posts",
    tool: "withdraw_job_application",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Sets job_applications.{id}.status='withdrawn' (the shape the client/admin applicant views read).",
  },
  {
    id: "caregiver-respond-interview",
    actor: "caregiver",
    action: "Respond to an interview request",
    webSurface: "components/caregiver/CaregiverBookingsPage.tsx",
    collection: "appointments",
    tool: "respond_to_interview_request",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-respond-booking-request",
    actor: "caregiver",
    action: "Accept/decline a booking request",
    webSurface: "components/caregiver/CaregiverBookingsPage.tsx",
    collection: "appointments",
    tool: "respond_to_booking_request",
    promptActor: "caregiver",
    status: "shipped",
    notes: "AE1. Accept drives the same appointment-confirmation path (status='confirmed', caregiverConfirmed) the web/shift-offer flow uses.",
  },
  {
    id: "caregiver-start-shift",
    actor: "caregiver",
    action: "Start a shift / clock in",
    webSurface: "components/caregiver/CaregiverHomeDashboard.tsx",
    collection: "shiftHours",
    tool: "start_shift",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Marks the visit in-progress + startedAt on the appointments (in_progress) or shifts (in-progress) doc the dashboard reads.",
  },
  {
    id: "caregiver-complete-shift",
    actor: "caregiver",
    action: "Complete a shift / clock out",
    webSurface: "components/caregiver/CaregiverHomeDashboard.tsx",
    collection: "shiftHours",
    tool: "complete_shift",
    promptActor: "caregiver",
    status: "shipped",
    notes: "AE7. Idempotent on SMS retry — an existing shiftHours record (or already-completed status) returns a no-op success, never double-billing.",
  },
  {
    id: "caregiver-update-shift-task",
    actor: "caregiver",
    action: "Toggle a visit task complete",
    webSurface: "components/caregiver/CaregiverHomeDashboard.tsx",
    collection: "appointments",
    tool: "update_shift_task",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Toggles shifts.{id}.tasksCompleted (recipient_careNeed[_subtask] keys) — the exact array the caregiver/family visit views read.",
  },
  {
    id: "caregiver-submit-media-update",
    actor: "caregiver",
    action: "Send a photo/media care update",
    webSurface: "components/caregiver/CaregiverHomeDashboard.tsx",
    collection: "care_journal",
    tool: "submit_media_update",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Writes a care_journal entry (entryType='media', media[]) the family care-journal/live-updates feed reads.",
  },
  {
    id: "caregiver-create-journal-entry",
    actor: "caregiver",
    action: "Create a care journal entry",
    webSurface: "components/caregiver/CareJournalEditor.tsx",
    collection: "care_journal",
    tool: "create_care_journal_entry",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-submit-shift-hours",
    actor: "caregiver",
    action: "Submit shift hours / timesheet",
    webSurface: "components/caregiver/CaregiverHomeDashboard.tsx",
    collection: "shiftHours",
    tool: "submit_shift_hours",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-respond-hour-correction",
    actor: "caregiver",
    action: "Respond to a shift-hour correction",
    webSurface: "components/caregiver/CaregiverPaymentsPage.tsx",
    collection: "shiftHours",
    tool: "respond_to_shift_hour_correction",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Transitions shiftHours from correction_requested/disputed: accept → pending_client_review with corrected hours; pushback → disputed + admin_alert.",
  },
  {
    id: "caregiver-request-instant-payout",
    actor: "caregiver",
    action: "Request an instant payout",
    webSurface: "components/caregiver/InstantPayoutModal.tsx",
    collection: "n/a",
    tool: "request_instant_payout",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Payout state is Stripe Connect; no registered Firestore contract collection.",
  },
  {
    id: "caregiver-request-standard-payout",
    actor: "caregiver",
    action: "Request a standard payout",
    webSurface: "components/caregiver/CaregiverPaymentsPage.tsx",
    collection: "n/a",
    tool: "request_standard_payout",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Same Stripe Connect eligibility gate as request_instant_payout (stripeAccountId + payoutsEnabled + available balance); uses method:'standard' (no fee). Payout state is Stripe Connect.",
  },
  {
    id: "caregiver-view-earnings",
    actor: "caregiver",
    action: "View earnings",
    webSurface: "components/caregiver/CaregiverPaymentsPage.tsx",
    collection: "n/a",
    tool: "get_caregiver_earnings",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Earnings are derived from Stripe/shiftHours; no dedicated contract collection.",
  },
  {
    id: "caregiver-tax-summary",
    actor: "caregiver",
    action: "View tax summary",
    webSurface: "components/caregiver/CaregiverPaymentsPage.tsx",
    collection: "n/a",
    tool: "get_tax_summary",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-message-client",
    actor: "caregiver",
    action: "Message a client",
    webSurface: "components/shared/MessagingPanel.tsx",
    collection: "threads",
    tool: "send_client_message",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-create-support-ticket",
    actor: "caregiver",
    action: "Open a support ticket",
    webSurface: "components/shared/SupportWidget.tsx",
    collection: "support_tickets",
    tool: "create_support_ticket",
    promptActor: "any",
    status: "shipped",
  },
  {
    id: "caregiver-check-background-status",
    actor: "caregiver",
    action: "Check background check status",
    webSurface: "components/caregiver/OnboardingChecklist.tsx",
    collection: "caregivers",
    tool: "get_background_check_status",
    promptActor: "caregiver",
    status: "shipped",
  },

  // ── Family (R1/R3 — secondary members) ─────────────────────────────────────
  {
    id: "family-read-care-journal",
    actor: "family",
    action: "Read care updates for the senior",
    webSurface: "components/client/CareJournalFeed.tsx",
    collection: "care_journal",
    tool: "get_care_journal_client",
    promptActor: "any",
    status: "shipped",
  },
  {
    id: "family-add-sibling",
    actor: "family",
    action: "Add another family member to the group",
    webSurface: "components/client/CareTeam.tsx",
    collection: "family_groups",
    tool: "add_family_member",
    promptActor: "any",
    status: "shipped",
    notes: "AE3 — added member receives a Linq welcome and the action is logged.",
  },

  // ── Admin exception handling (R3) ──────────────────────────────────────────
  {
    id: "admin-review-caregiver-exception",
    actor: "admin",
    action: "Resolve a Checkr consider/exception in the verification queue",
    webSurface: "components/admin/CaregiverVerificationDashboard.tsx",
    collection: "caregivers",
    tool: "admin_review_caregiver_exception",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3 — AE8/R8. Admin-gated callable. A manual approve sets verificationStatus but only flips status:'active' (bookable) when onboardingStatus profile_complete AND verificationStatus approved both hold; never fabricates a Checkr clear.",
  },
  {
    id: "admin-review-document",
    actor: "admin",
    action: "Approve/reject an uploaded caregiver document",
    webSurface: "components/admin/CaregiverVerificationDashboard.tsx",
    collection: "caregivers",
    tool: "admin_review_document",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3 — admin-gated callable; sets documents.{type}.status approved/rejected.",
  },
  {
    id: "admin-suspend-user",
    actor: "admin",
    action: "Suspend a user (soft, audit-logged)",
    webSurface: "components/admin/UserManagement.tsx",
    collection: "users",
    tool: "admin_suspend_user",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3 — admin-gated callable; soft accountStatus:'suspended' (never destructive delete), audit-logged.",
  },
  {
    id: "admin-restore-user",
    actor: "admin",
    action: "Restore a suspended user",
    webSurface: "components/admin/UserManagement.tsx",
    collection: "users",
    tool: "admin_restore_user",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3 — counterpart callable; clears suspension (accountStatus:'active').",
  },
  {
    id: "admin-respond-support-ticket",
    actor: "admin",
    action: "Respond to a support ticket so the user sees the reply",
    webSurface: "components/admin/TicketManager.tsx",
    collection: "support_tickets",
    tool: "admin_respond_support_ticket",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3 — admin-gated callable; writes the user-visible responses subcollection + notifies via Linq/notifications.",
  },
  {
    id: "admin-resolve-dispute",
    actor: "admin",
    action: "Resolve a shift-hour/payment dispute with audit log",
    webSurface: "components/admin/InvoicingTab.tsx",
    collection: "shiftHours",
    tool: "admin_resolve_dispute",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3 — admin-gated callable; transitions shiftHours to terminal approved/rejected + correctionHistory + audit.",
  },
  {
    id: "admin-review-invoice-exception",
    actor: "admin",
    action: "Review an invoice exception (payment_failed, etc.)",
    webSurface: "components/admin/InvoicingTab.tsx",
    collection: "admin_alerts",
    tool: "admin_review_invoice_exception",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3 — admin-gated callable; invoice exceptions surface as admin_alerts; records resolution + audit.",
  },
  {
    id: "admin-retry-agent-action",
    actor: "admin",
    action: "Retry/replay a failed agent action from the ledger",
    webSurface: "components/admin/AdminCaraControlRoom.tsx",
    collection: "agent_action_ledger",
    tool: "admin_retry_agent_action",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3/U4 — AE5. Admin-gated callable; re-dispatches the recorded tool, marks the ledger executed/failed (never false success), idempotency-keyed against double-retry.",
  },

  // ── Explicit non-goals (Scope Boundaries — Out Of Scope) ───────────────────
  {
    id: "nongoal-medical-advice",
    actor: "client",
    action: "Diagnose, prescribe, or give medical advice",
    webSurface: "n/a",
    collection: "n/a",
    tool: null,
    promptActor: null,
    status: "non-goal",
    notes: "R7 — Cara avoids medical advice and routes emergencies to 911 guidance.",
  },
  {
    id: "nongoal-raw-card-capture",
    actor: "client",
    action: "Collect raw card numbers / portal passwords in chat text",
    webSurface: "n/a",
    collection: "n/a",
    tool: null,
    promptActor: null,
    status: "non-goal",
    notes: "Out of scope — payment changes go through Stripe-hosted links only.",
  },
  {
    id: "nongoal-bookable-without-checkr",
    actor: "admin",
    action: "Make a caregiver bookable without completed onboarding + Checkr clear",
    webSurface: "n/a",
    collection: "caregivers",
    tool: null,
    promptActor: null,
    status: "non-goal",
    notes: "R8 — bookability requires onboardingStatus profile_complete + verificationStatus approved.",
  },
];
