// Evia launch action-parity registry.
//
// The launch promise: **anything a user can do on the web, Evia can do over
// SMS.** This module is the single, machine-checkable map of every
// launch-critical client / caregiver / admin action to the Evia MCP tool (or
// handler) that performs it. context/capability-map.md is the human-readable
// mirror; THIS file is the source of truth.
//
// toolCapabilities.test.ts enforces the invariants:
//   • shipped rows point at a real MCP_TOOLS tool
//   • blocker rows carry tool:null (a gap must not claim a shipped tool)
//   • every collection is "n/a" or a key in CONTRACT_COLLECTIONS
//   • shipped caregiver-actor tools are reachable by the caregiver prompt filter
//
// Status meanings:
//   shipped   — the tool exists in MCP_TOOLS today and is wired to the web-read
//               Firestore shape.
//   blocker   — launch-critical parity gap. tool MUST be null. The intended tool
//               name lives in `action`. U2 (caregiver) and U3 (admin) flip these
//               to shipped.
//   non-goal  — explicitly out of scope per the plan's Scope Boundaries
//               (medical advice, raw card capture, bookable-without-Checkr).

export interface LaunchAction {
  /** Stable kebab id, e.g. "client-book-caregiver". Unique across the registry. */
  id: string;
  actor: "client" | "caregiver" | "admin" | "family";
  /** Human description of the action (for blocker rows, name the intended tool here). */
  action: string;
  /** Component/page that performs this on the web. */
  webSurface: string;
  /** Primary Firestore collection. "n/a" or a key in CONTRACT_COLLECTIONS. */
  collection: string;
  /** Evia MCP tool name (or handler). null only when status is "blocker" or "non-goal". */
  tool: string | null;
  /**
   * Which prompt/tool-filter actor should expose this tool:
   *   "client" | "caregiver" | "admin" — actor-specific prompt surface.
   *   "any"  — cross-cutting tool exposed regardless of actor (core reads,
   *            messaging, support, journal that both sides touch).
   *   null   — no tool is exposed yet (blocker / non-goal rows).
   */
  promptActor: "client" | "caregiver" | "admin" | "any" | null;
  status: "shipped" | "blocker" | "non-goal";
  /**
   * How the action is exposed:
   *   "mcp"      — an Evia MCP tool in MCP_TOOLS (default when undefined).
   *   "callable" — a Firebase https.onCall callable exported from
   *                functions/src/index.ts (admin execution actions, U3). These
   *                are NOT exposed as client/caregiver MCP tools; `tool` names
   *                the callable export.
   */
  surface?: "mcp" | "callable";
  /** Optional clarification — why blocked, which unit ships it, scope rationale. */
  notes?: string;
}

export const LAUNCH_ACTION_PARITY: readonly LaunchAction[] = [
  // ── Client (R1) ───────────────────────────────────────────────────────────
  {
    id: "client-find-caregiver",
    actor: "client",
    action: "Search/match caregivers (website Browse / Nearby Caregivers)",
    webSurface: "components/FindCaregivers.tsx",
    collection: "caregivers",
    tool: "find_nearby_caregivers",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-book-caregiver",
    actor: "client",
    action: "Send a booking request to an interviewed caregiver (the site's Send Booking Request modal — one booking_requests doc, status pending)",
    webSurface: "components/client/PostsPage.tsx",
    collection: "booking_requests",
    tool: "start_booking_flow",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-cancel-appointment",
    actor: "client",
    action: "Cancel an appointment (manage_booking action: cancel_pending_request / cancel_whole_booking)",
    webSurface: "components/client/ClientVisitsPage.tsx",
    collection: "shifts",
    tool: "manage_booking",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-update-care-plan",
    actor: "client",
    action: "Update the senior's care plan",
    webSurface: "components/CarePlan.tsx",
    collection: "carePlans",
    tool: "update_care_plan",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-set-recipient-photo",
    actor: "client",
    action: "Set a care recipient's photo (the tab avatar)",
    webSurface: "components/CarePlan.tsx",
    collection: "job_postings",
    tool: "set_recipient_photo",
    promptActor: "client",
    status: "shipped",
    notes: "Over text the file is the photo the family attached (stored by the inbound media handler); same storage folder + roster field as the page.",
  },
  {
    id: "client-add-family-member",
    actor: "client",
    action: "Add a member to the family group",
    webSurface: "components/client/MyCareTeam.tsx",
    collection: "family_groups",
    tool: "add_family_member",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-remove-family-member",
    actor: "client",
    action: "Remove a member from the family group",
    webSurface: "components/client/MyCareTeam.tsx",
    collection: "family_groups",
    tool: "remove_family_member",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-read-care-journal",
    actor: "client",
    action: "Read the care journal / visit updates",
    webSurface: "components/client/CareJournalFeed.tsx",
    collection: "care_journal",
    tool: "get_care_journal_client",
    promptActor: "any",
    status: "shipped",
  },
  {
    id: "client-message-caregiver",
    actor: "client",
    action: "Message a caregiver",
    webSurface: "components/InboxView.tsx",
    collection: "threads",
    tool: "send_caregiver_message",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-create-support-ticket",
    actor: "client",
    action: "Open a support ticket",
    webSurface: "components/shared/SupportChatModal.tsx",
    collection: "support_tickets",
    tool: "create_support_ticket",
    promptActor: "any",
    status: "shipped",
  },
  {
    id: "client-update-payment-method",
    actor: "client",
    action: "Payment Method tab (card on file, Add a card / Manage payment method)",
    webSurface: "components/client/Payments.tsx",
    collection: "n/a",
    tool: "get_payment_update_link",
    promptActor: "any",
    status: "shipped",
    notes: "Same reads as the page: customers/{uid}.stripeCustomerId + the live Stripe card check (getPaymentMethodStatusFor); Add a card → /client/membership, Manage → Billing Portal. Raw card details never in chat.",
  },
  {
    id: "client-view-timesheets",
    actor: "client",
    action: "Timesheets page — Needs Review + History (with date-range totals)",
    webSurface: "components/client/Payments.tsx",
    collection: "shiftHours",
    tool: "get_pending_timesheets",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-approve-timesheet",
    actor: "client",
    action: "Review shift hours (approve / propose correction / accept counter / escalate)",
    webSurface: "components/payroll/ReviewShiftHoursModal.tsx",
    collection: "shiftHours",
    tool: "review_shift_hours",
    promptActor: "client",
    status: "shipped",
    notes: "Runs the callable's own function (billing/reviewShiftHours.ts reviewShiftHoursAs) — one write path with the website.",
  },
  {
    id: "client-retry-shift-payment",
    actor: "client",
    action: "Retry a failed shift payment",
    webSurface: "components/client/Payments.tsx",
    collection: "shiftHours",
    tool: "retry_shift_payment",
    promptActor: "client",
    status: "shipped",
    notes: "Parity audit 2026-07-06: agent mirror of v1-retryShiftPayment — resets payment_failed → approved so the charge trigger re-fires. Owner-scoped; naturally idempotent (a replay finds status !== payment_failed).",
  },
  {
    id: "client-submit-review",
    actor: "client",
    action: "Submit a caregiver review",
    webSurface: "components/client/LeaveReviewModal.tsx",
    collection: "reviews",
    tool: "start_review_flow",
    promptActor: "client",
    status: "shipped",
  },
  {
    id: "client-view-upcoming-appointments",
    actor: "client",
    action: "Read upcoming appointments",
    webSurface: "components/client/ClientVisitsPage.tsx",
    collection: "appointments",
    tool: "get_upcoming_appointments",
    promptActor: "any",
    status: "shipped",
    notes: "Used by Evia recipe discovery for next-visit briefing and visit confirmation context.",
  },
  {
    id: "client-view-care-team",
    actor: "client",
    action: "Read the client's care team",
    webSurface: "components/client/MyCareTeam.tsx",
    collection: "caregivers",
    tool: "get_care_team",
    promptActor: "any",
    status: "shipped",
    notes: "Used by Evia recipe discovery for next-visit and who-is-coming answers.",
  },
  {
    id: "client-review-cara-memory",
    actor: "client",
    action: "Review what Evia remembers",
    webSurface: "n/a",
    collection: "n/a",
    tool: "cara_knows",
    promptActor: "any",
    status: "shipped",
    notes: "Memory is derived from scoped memory files, Zep context, learned facts, and live tool data; hidden prompt context is not exposed.",
  },
  {
    id: "client-update-cara-memory",
    actor: "client",
    action: "Correct or update Evia memory",
    webSurface: "n/a",
    collection: "n/a",
    tool: "update_memory_file",
    promptActor: "any",
    status: "shipped",
    notes: "Fresh corrections outrank stale memory and learned facts.",
  },

  // ── Client CRUD/parity gap closures (agent-native audit 2026-07) ──────────
  {
    id: "client-archive-senior-profile",
    actor: "client",
    action: "Archive (soft-delete) a senior profile when care ends",
    webSurface: "n/a",
    collection: "senior_profiles",
    tool: "archive_senior_profile",
    promptActor: "client",
    status: "shipped",
    notes: "Soft status flag only (status:'archived'); the care record is retained. Hard delete is an intentional exclusion (AGENT_NATIVE_EXCLUSIONS.md).",
  },
  {
    id: "client-update-family-member",
    actor: "client",
    action: "Edit a family group member's name/role/relationship/notifications",
    webSurface: "components/client/MyCareTeam.tsx",
    collection: "family_group_members",
    tool: "update_family_member",
    promptActor: "client",
    status: "shipped",
    notes: "Ownership scoped by the userId+memberPhone query — only the caller's own membership docs are reachable.",
  },
  {
    id: "client-list-interviews",
    actor: "client",
    action: "List scheduled/pending interviews",
    webSurface: "n/a",
    collection: "video_interviews",
    tool: "list_interviews",
    promptActor: "any",
    status: "shipped",
    notes: "Caller-scoped read (clientId OR caregiverId); exposed to both actors.",
  },
  {
    id: "client-cancel-interview",
    actor: "client",
    action: "Cancel a scheduled interview",
    webSurface: "n/a",
    collection: "video_interviews",
    tool: "cancel_interview",
    promptActor: "any",
    status: "shipped",
    notes: "Either participant can cancel their own interview; the counterpart is notified (trySend for caregivers, Linq session for clients).",
  },
  {
    id: "client-reschedule-interview",
    actor: "client",
    action: "Propose a new date/time for an already-scheduled interview, in place (no cancel)",
    webSurface: "components/client/PostsPage.tsx, components/caregiver/JobBoard.tsx",
    collection: "video_interviews",
    tool: "reschedule_interview",
    promptActor: "any",
    status: "shipped",
    notes: "Writes reschedulePendingTime/rescheduledBy only — never touches scheduledTime/status until accepted. Matches the site's Reschedule/Propose different time button exactly (2026-09-12).",
  },
  {
    id: "client-accept-interview-reschedule",
    actor: "client",
    action: "Confirm the other party's pending proposed interview time",
    webSurface: "components/client/PostsPage.tsx, components/caregiver/JobBoard.tsx",
    collection: "video_interviews",
    tool: "accept_interview_reschedule",
    promptActor: "any",
    status: "shipped",
    notes: "The moment scheduledTime actually changes. Matches the site's Accept new time button exactly (2026-09-12).",
  },
  {
    id: "client-delete-memory-file",
    actor: "client",
    action: "Delete an Evia memory file (content + search index)",
    webSurface: "n/a",
    collection: "n/a",
    tool: "delete_memory_file",
    promptActor: "any",
    status: "shipped",
    notes: "Memory files live in Storage (memory/{userId}/), not a Firestore contract collection; block embeddings are purged with the file.",
  },
  {
    id: "client-list-blocked-users",
    actor: "client",
    action: "List blocked users",
    webSurface: "components/InboxView.tsx",
    collection: "users",
    tool: "list_blocked_users",
    promptActor: "client",
    status: "shipped",
    notes: "Read primitive over users.{uid}.blockedUsers (the array set_block_status maintains).",
  },

  // ── Caregiver (R2) ────────────────────────────────────────────────────────
  {
    id: "caregiver-update-profile",
    actor: "caregiver",
    action: "Update caregiver profile (rate/skills/bio)",
    webSurface: "components/CaregiverProfile.tsx",
    collection: "caregivers",
    tool: "update_caregiver_profile",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-update-availability",
    actor: "caregiver",
    action: "Update availability",
    webSurface: "components/caregiver/CaregiverCalendarPage.tsx",
    collection: "caregivers",
    tool: "update_caregiver_availability",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-browse-jobs",
    actor: "caregiver",
    action: "Browse the job board",
    webSurface: "components/caregiver/JobBoard.tsx",
    collection: "job_posts",
    tool: "browse_job_board",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-apply-to-job",
    actor: "caregiver",
    action: "Apply to a job post",
    webSurface: "components/caregiver/JobBoard.tsx",
    collection: "job_posts",
    tool: "apply_to_job",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-withdraw-application",
    actor: "caregiver",
    action: "Withdraw a job application",
    webSurface: "components/caregiver/JobBoard.tsx",
    collection: "job_posts",
    tool: "withdraw_job_application",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Sets job_applications.{id}.status='withdrawn' (the shape the client/admin applicant views read).",
  },
  {
    id: "caregiver-respond-interview",
    actor: "caregiver",
    action: "Respond to an interview request",
    webSurface: "components/caregiver/CaregiverCalendarPage.tsx",
    collection: "video_interviews",
    tool: "respond_to_interview_request",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Accept notifies the client with the Google Meet join link (callUrl on the doc).",
  },
  {
    id: "client-schedule-interview",
    actor: "client",
    action: "Schedule a video interview with a caregiver",
    webSurface: "components/ScheduleInterviewModal.tsx",
    collection: "video_interviews",
    tool: "schedule_interview",
    promptActor: "client",
    status: "shipped",
    notes: "Generates the Google Meet link inline (callUrl in the create payload) and texts it to the caregiver; interviewLinkTrigger covers the web-modal path.",
  },
  {
    id: "caregiver-respond-booking-request",
    actor: "caregiver",
    action: "Accept/decline a booking request",
    webSurface: "components/caregiver/CaregiverBookingsPage.tsx",
    collection: "appointments",
    tool: "respond_to_booking_request",
    promptActor: "caregiver",
    status: "shipped",
    notes: "AE1. Accept drives the same appointment-confirmation path (status='confirmed', caregiverConfirmed) the web/shift-offer flow uses.",
  },
  {
    id: "caregiver-start-shift",
    actor: "caregiver",
    action: "Start a shift / clock in",
    webSurface: "components/caregiver/CaregiverHomeDashboard.tsx",
    collection: "shiftHours",
    tool: "start_shift",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Marks the visit in-progress + startedAt on the appointments (in_progress) or shifts (in-progress) doc the dashboard reads.",
  },
  {
    id: "caregiver-complete-shift",
    actor: "caregiver",
    action: "Complete a shift / clock out",
    webSurface: "components/caregiver/CaregiverHomeDashboard.tsx",
    collection: "shiftHours",
    tool: "complete_shift",
    promptActor: "caregiver",
    status: "shipped",
    notes: "AE7. Idempotent on SMS retry — an existing shiftHours record (or already-completed status) returns a no-op success, never double-billing.",
  },
  {
    id: "caregiver-update-shift-task",
    actor: "caregiver",
    action: "Toggle a visit task complete",
    webSurface: "components/caregiver/CaregiverHomeDashboard.tsx",
    collection: "appointments",
    tool: "update_shift_task",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Toggles shifts.{id}.tasksCompleted (recipient_careNeed[_subtask] keys) — the exact array the caregiver/family visit views read.",
  },
  {
    id: "caregiver-submit-media-update",
    actor: "caregiver",
    action: "Send a photo/media care update",
    webSurface: "components/caregiver/CaregiverHomeDashboard.tsx",
    collection: "care_journal",
    tool: "submit_media_update",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Writes a care_journal entry (entryType='media', media[]) the family care-journal/live-updates feed reads.",
  },
  {
    id: "caregiver-create-journal-entry",
    actor: "caregiver",
    action: "Create a care journal entry",
    webSurface: "components/caregiver/CaregiverHomeDashboard.tsx",
    collection: "care_journal",
    tool: "create_care_journal_entry",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-submit-shift-hours",
    actor: "caregiver",
    action: "Submit shift hours / timesheet",
    webSurface: "components/caregiver/CaregiverHomeDashboard.tsx",
    collection: "shiftHours",
    tool: "submit_shift_hours",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-respond-hour-correction",
    actor: "caregiver",
    action: "Respond to a shift-hour correction",
    webSurface: "components/caregiver/CaregiverPaymentsPage.tsx",
    collection: "shiftHours",
    tool: "respond_to_shift_hour_correction",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Transitions shiftHours from correction_proposed (plus legacy correction_requested/disputed reads): accept → pending_client_review with corrected hours; pushback → disputed_admin_review + admin_alert.",
  },
  {
    id: "caregiver-request-instant-payout",
    actor: "caregiver",
    action: "Request an instant payout",
    webSurface: "components/caregiver/InstantPayoutModal.tsx",
    collection: "n/a",
    tool: "request_instant_payout",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Payout state is Stripe Connect; no registered Firestore contract collection.",
  },
  // caregiver-request-standard-payout removed 2026-07-06: standard payouts are
  // automatic (Stripe daily schedule) — there is no user action to mirror.
  {
    id: "caregiver-view-earnings",
    actor: "caregiver",
    action: "View earnings",
    webSurface: "components/caregiver/CaregiverPaymentsPage.tsx",
    collection: "n/a",
    tool: "get_caregiver_earnings",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Earnings are derived from Stripe/shiftHours; no dedicated contract collection.",
  },
  {
    id: "caregiver-tax-summary",
    actor: "caregiver",
    action: "View tax summary",
    webSurface: "components/caregiver/CaregiverPaymentsPage.tsx",
    collection: "n/a",
    tool: "get_tax_summary",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-message-client",
    actor: "caregiver",
    action: "Message a client",
    webSurface: "components/InboxView.tsx",
    collection: "threads",
    tool: "send_client_message",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-refer-caregiver",
    actor: "caregiver",
    action: "Refer another caregiver",
    webSurface: "n/a",
    collection: "referrals",
    tool: "create_caregiver_referral",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Writes non-bookable caregiver referrals, sends the SMS invite, and keeps bookability gated on onboardingStatus='profile_complete', verificationStatus='approved', and Checkr clear.",
  },
  {
    id: "caregiver-create-support-ticket",
    actor: "caregiver",
    action: "Open a support ticket",
    webSurface: "components/shared/SupportChatModal.tsx",
    collection: "support_tickets",
    tool: "create_support_ticket",
    promptActor: "any",
    status: "shipped",
  },
  {
    id: "caregiver-check-background-status",
    actor: "caregiver",
    action: "Check background check status",
    webSurface: "components/caregiver/CaregiverOnboardingDashboard.tsx",
    collection: "caregivers",
    tool: "get_background_check_status",
    promptActor: "caregiver",
    status: "shipped",
  },
  {
    id: "caregiver-upload-intro-video",
    actor: "caregiver",
    action: "Upload an intro video to the caregiver profile (intended tool: update to update_caregiver_profile or a media pipeline route into caregivers.introVideoUrl)",
    webSurface: "components/caregiver/CaregiverIntroVideo.tsx",
    collection: "caregivers",
    tool: null,
    promptActor: null,
    status: "blocker",
    notes: "Parity audit 2026-07-06: web-only write to caregivers.introVideoUrl — update_caregiver_profile excludes it and no SMS media pipeline routes a texted video there. Should-have (not launch-critical): needs a Storage upload path for SMS media before the tool is honest.",
  },

  // ── Caregiver CRUD/parity gap closures (agent-native audit 2026-07) ────────
  {
    id: "caregiver-list-shift-swaps",
    actor: "caregiver",
    action: "List active shift swap requests and open peer offers",
    webSurface: "components/caregiver/CaregiverBookingsPage.tsx",
    collection: "shift_swap_requests",
    tool: "list_shift_swaps",
    promptActor: "caregiver",
    status: "shipped",
    notes: "Read primitive over the collection request_shift_swap/accept_shift_swap write: the caller's own requests plus unexpired open offers from peers.",
  },

  // ── Family (R1/R3 — secondary members) ─────────────────────────────────────
  {
    id: "family-read-care-journal",
    actor: "family",
    action: "Read care updates for the senior",
    webSurface: "components/client/CareJournalFeed.tsx",
    collection: "care_journal",
    tool: "get_care_journal_client",
    promptActor: "any",
    status: "shipped",
  },
  {
    id: "family-add-sibling",
    actor: "family",
    action: "Add another family member to the group",
    webSurface: "components/client/MyCareTeam.tsx",
    collection: "family_groups",
    tool: "add_family_member",
    promptActor: "any",
    status: "shipped",
    notes: "AE3 — added member receives a Linq welcome and the action is logged.",
  },

  // ── Admin exception handling (R3) ──────────────────────────────────────────
  {
    id: "admin-review-caregiver-exception",
    actor: "admin",
    action: "Resolve a Checkr consider/exception in the verification queue",
    webSurface: "components/admin/CaregiverVerificationDashboard.tsx",
    collection: "caregivers",
    tool: "admin_review_caregiver_exception",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3 — AE8/R8. Admin-gated callable. A manual approve sets verificationStatus but only flips status:'active' (bookable) when onboardingStatus profile_complete AND verificationStatus approved both hold; never fabricates a Checkr clear.",
  },
  {
    id: "admin-review-document",
    actor: "admin",
    action: "Approve/reject an uploaded caregiver document",
    webSurface: "components/admin/CaregiverVerificationDashboard.tsx",
    collection: "caregivers",
    tool: "admin_review_document",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3 — admin-gated callable; sets documents.{type}.status approved/rejected.",
  },
  {
    id: "admin-suspend-user",
    actor: "admin",
    action: "Suspend a user (soft, audit-logged)",
    webSurface: "components/admin/AdminClientManager.tsx",
    collection: "users",
    tool: "admin_suspend_user",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3 — admin-gated callable; soft accountStatus:'suspended' (never destructive delete), audit-logged.",
  },
  {
    id: "admin-restore-user",
    actor: "admin",
    action: "Restore a suspended user",
    webSurface: "components/admin/AdminClientManager.tsx",
    collection: "users",
    tool: "admin_restore_user",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3 — counterpart callable; clears suspension (accountStatus:'active').",
  },
  {
    id: "admin-respond-support-ticket",
    actor: "admin",
    action: "Respond to a support ticket so the user sees the reply",
    webSurface: "components/admin/TicketManager.tsx",
    collection: "support_tickets",
    tool: "admin_respond_support_ticket",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3 — admin-gated callable; writes the user-visible responses subcollection + notifies via Linq/notifications.",
  },
  {
    id: "admin-resolve-dispute",
    actor: "admin",
    action: "Resolve a shift-hour/payment dispute with audit log",
    webSurface: "components/admin/InvoicingTab.tsx",
    collection: "shiftHours",
    tool: "admin_resolve_dispute",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3 — admin-gated callable; transitions shiftHours to terminal approved/rejected + correctionHistory + audit.",
  },
  {
    id: "admin-review-invoice-exception",
    actor: "admin",
    action: "Review an invoice exception (payment_failed, etc.)",
    webSurface: "components/admin/InvoicingTab.tsx",
    collection: "admin_alerts",
    tool: "admin_review_invoice_exception",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3 — admin-gated callable; invoice exceptions surface as admin_alerts; records resolution + audit.",
  },
  {
    id: "admin-retry-agent-action",
    actor: "admin",
    action: "Retry/replay a failed agent action from the ledger",
    webSurface: "components/admin/AdminCaraControlRoom.tsx",
    collection: "agent_action_ledger",
    tool: "admin_retry_agent_action",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U3/U4 — AE5. Admin-gated callable; re-dispatches the recorded tool, marks the ledger executed/failed (never false success), idempotency-keyed against double-retry.",
  },
  {
    id: "admin-retry-linq-delivery",
    actor: "admin",
    action: "Re-attempt a failed Linq outbound delivery",
    webSurface: "components/admin/AdminCaraControlRoom.tsx",
    collection: "agent_action_ledger",
    tool: "admin_retry_linq_delivery",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U4 — AE5/R16. Admin-gated callable; reuses the production Linq send path, transitions the ledger failed→executed on success, raises admin_alerts on failure (no false success), idempotency-keyed.",
  },
  {
    id: "admin-replay-pending-action",
    actor: "admin",
    action: "Replay a safe pending action via the MCP executor",
    webSurface: "components/admin/AdminCaraControlRoom.tsx",
    collection: "pending_actions",
    tool: "admin_replay_pending_action",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U4 — R6/R16. Admin-gated callable; re-runs the tool through handleToolCall. High-risk replays (isHighRisk) require confirm:true; idempotency-keyed against double-execute; fails visibly with admin_alerts.",
  },
  {
    id: "admin-cancel-pending-action",
    actor: "admin",
    action: "Cancel a stale pending action without executing it",
    webSurface: "components/admin/AdminCaraControlRoom.tsx",
    collection: "pending_actions",
    tool: "admin_cancel_pending_action",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U4 — R16. Admin-gated callable; transitions to terminal rejected/cancelled WITHOUT calling the underlying tool; reason required; idempotent on already-terminal docs.",
  },
  {
    id: "admin-assign-recovery-owner",
    actor: "admin",
    action: "Assign a recovery owner on a ledger/alert doc",
    webSurface: "components/admin/AdminCaraControlRoom.tsx",
    collection: "agent_action_ledger",
    tool: "admin_assign_recovery_owner",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U4 — R16. Admin-gated callable; sets owner/assignee on agent_action_ledger or admin_alerts for operator accountability; no tool execution.",
  },
  {
    id: "admin-mark-recovery-complete",
    actor: "admin",
    action: "Mark manual recovery complete on a ledger/alert doc",
    webSurface: "components/admin/AdminCaraControlRoom.tsx",
    collection: "agent_action_ledger",
    tool: "admin_mark_recovery_complete",
    promptActor: "admin",
    surface: "callable",
    status: "shipped",
    notes: "U4 — R16. Admin-gated callable; reason REQUIRED (invalid-argument otherwise); marks ledger handled/cancelled or resolves the alert; no tool execution.",
  },

  // ── Explicit non-goals (Scope Boundaries — Out Of Scope) ───────────────────
  {
    id: "nongoal-medical-advice",
    actor: "client",
    action: "Diagnose, prescribe, or give medical advice",
    webSurface: "n/a",
    collection: "n/a",
    tool: null,
    promptActor: null,
    status: "non-goal",
    notes: "R7 — Evia avoids medical advice and routes emergencies to 911 guidance.",
  },
  {
    id: "nongoal-raw-card-capture",
    actor: "client",
    action: "Collect raw card numbers / portal passwords in chat text",
    webSurface: "n/a",
    collection: "n/a",
    tool: null,
    promptActor: null,
    status: "non-goal",
    notes: "Out of scope — payment changes go through Stripe-hosted links only.",
  },
  {
    id: "nongoal-bookable-without-checkr",
    actor: "admin",
    action: "Make a caregiver bookable without completed onboarding + Checkr clear",
    webSurface: "n/a",
    collection: "caregivers",
    tool: null,
    promptActor: null,
    status: "non-goal",
    notes: "R8 — bookability requires onboardingStatus profile_complete + verificationStatus approved.",
  },
];
