// Runtime-enforced confirmation gate for irreversible tool calls.
//
// Today Cara is *told* in the system prompt to confirm before
// cancel_appointment, delete_reminder, etc. — but if she forgets or is
// prompt-injected, the action fires immediately. One bad incident in
// eldercare is irrecoverable, so we enforce confirmation in the runtime.
//
// Flow:
//   1. Claude calls a high-risk tool inside the qa loop.
//   2. MCP dispatcher routes through this module instead of executing.
//   3. proposePendingAction() writes a Firestore doc with the tool name,
//      args, and a 15-min TTL, and returns a structured stub for Claude.
//   4. Claude reads the stub, generates a confirmation message to the family.
//   5. Family replies. approvalHandler classifies YES / NO / QUESTION.
//   6. On YES, the MCP gate re-runs the tool with _confirmedActionId set,
//      which bypasses this gate and executes normally.
//   7. On NO, the action is marked rejected.
//   8. On timeout / 15-min expiry, the action is unusable; a subsequent YES
//      from the family won't re-trigger anything.

import * as admin from "firebase-admin";

const db = admin.firestore();

export const PENDING_ACTION_TTL_MS = 15 * 60 * 1000; // 15 minutes

export interface PendingAction {
  id:           string;
  phone:        string;
  userId?:      string;
  toolName:     string;
  toolInput:    Record<string, unknown>;
  preview:      string;
  proposedAt:   string; // ISO
  expiresAt:    string; // ISO — proposedAt + TTL
  status:       "awaiting" | "approved" | "rejected" | "expired" | "executed" | "failed";
  resolvedAt?:  string;
  // Truncated executed-result preview for debugging; not the full payload.
  executionPreview?: string;
}

// Set of tool names that ALWAYS require confirmation regardless of args.
// Mirrors the qaAgent.ts system-prompt list. Adding a tool here is a
// production-safety change; review the prompt's confirmation guidance too.
const ALWAYS_CONFIRM = new Set<string>([
  "cancel_appointment",
  "delete_reminder",
  "remove_family_member",
  "cancel_subscription",
  "restore_care_plan_version",
  "block_user",
  "report_user",
  "cancel_job_post",
]);

// Tools whose risk depends on an argument value. The predicate inspects the
// input and returns true when this specific call is irreversible.
const CONDITIONAL_CONFIRM: Record<string, (input: Record<string, unknown>) => boolean> = {
  // Only cancel — pause and resume are reversible.
  manage_recurring_schedule: (input) => input.action === "cancel",
  // Rejecting an applicant is irreversible (caregiver sees the decline).
  // Accept is also high-stakes but happens via a separate hire flow.
  respond_to_job_application: (input) => input.decision === "reject",
};

export function isHighRisk(toolName: string, toolInput: Record<string, unknown>): boolean {
  if (ALWAYS_CONFIRM.has(toolName)) return true;
  const pred = CONDITIONAL_CONFIRM[toolName];
  return pred ? pred(toolInput) : false;
}

// Build a short human-readable preview of the action so support / debugging
// can see what was proposed without parsing the raw input JSON. Falls back
// to a generic summary when no special-cased shape applies.
export function buildActionPreview(toolName: string, toolInput: Record<string, unknown>): string {
  switch (toolName) {
    case "cancel_appointment":
      return `Cancel appointment ${String(toolInput.appointmentId ?? "?")}`;
    case "delete_reminder":
      return `Delete reminder ${String(toolInput.reminderId ?? "?")}`;
    case "remove_family_member":
      return `Remove family member ${String(toolInput.memberPhone ?? toolInput.memberId ?? "?")}`;
    case "cancel_subscription":
      return `Cancel CareConnex subscription`;
    case "restore_care_plan_version":
      return `Restore care plan to version ${String(toolInput.versionId ?? "?")}`;
    case "block_user":
      return `Block user ${String(toolInput.targetUserId ?? toolInput.targetPhone ?? "?")}`;
    case "report_user":
      return `Report user ${String(toolInput.targetUserId ?? toolInput.targetPhone ?? "?")}`;
    case "cancel_job_post":
      return `Cancel job post ${String(toolInput.jobId ?? "?")}`;
    case "manage_recurring_schedule":
      return `${String(toolInput.action ?? "modify")} recurring schedule ${String(toolInput.scheduleId ?? "")}`.trim();
    case "respond_to_job_application":
      return `${String(toolInput.decision ?? "respond to")} application ${String(toolInput.applicationId ?? "")}`.trim();
    default:
      return `${toolName} (irreversible)`;
  }
}

// Write a new pending action and return the doc. The id is generated by
// Firestore; callers use it to bypass the gate on the approval re-run.
export async function proposePendingAction(params: {
  phone:     string;
  userId?:   string;
  toolName:  string;
  toolInput: Record<string, unknown>;
}): Promise<PendingAction> {
  const now = Date.now();
  const action: Omit<PendingAction, "id"> = {
    phone:      params.phone,
    userId:     params.userId,
    toolName:   params.toolName,
    toolInput:  params.toolInput,
    preview:    buildActionPreview(params.toolName, params.toolInput),
    proposedAt: new Date(now).toISOString(),
    expiresAt:  new Date(now + PENDING_ACTION_TTL_MS).toISOString(),
    status:     "awaiting",
  };
  const ref = await db.collection("pending_actions").add(action);
  return { id: ref.id, ...action };
}

// Look up the most recent unresolved pending action for a phone, or null.
// "Unresolved" = status === "awaiting" AND expiresAt > now.
// Auto-expires stale awaiting docs so they don't accumulate.
export async function getLatestPending(phone: string): Promise<PendingAction | null> {
  const snap = await db.collection("pending_actions")
    .where("phone",  "==", phone)
    .where("status", "==", "awaiting")
    .orderBy("proposedAt", "desc")
    .limit(1)
    .get();
  if (snap.empty) return null;
  const doc  = snap.docs[0];
  const data = doc.data() as Omit<PendingAction, "id">;

  if (new Date(data.expiresAt).getTime() < Date.now()) {
    // Lazily expire — keeps the read fast at the cost of one write per stale doc.
    await doc.ref.update({
      status:     "expired",
      resolvedAt: new Date().toISOString(),
    }).catch(() => {});
    return null;
  }
  return { id: doc.id, ...data };
}

export async function getPendingActionById(id: string): Promise<PendingAction | null> {
  const snap = await db.collection("pending_actions").doc(id).get();
  if (!snap.exists) return null;
  return { id: snap.id, ...(snap.data() as Omit<PendingAction, "id">) };
}

// Mark resolved with the given status. Idempotent — calling twice with the
// same status is a no-op; calling with a different status logs a warning so
// downstream race conditions surface.
export async function resolvePendingAction(
  id: string,
  status: Exclude<PendingAction["status"], "awaiting">,
  opts: { executionPreview?: string } = {},
): Promise<void> {
  const ref = db.collection("pending_actions").doc(id);
  await db.runTransaction(async (tx) => {
    const snap = await tx.get(ref);
    if (!snap.exists) return;
    const current = snap.data() as PendingAction;
    if (current.status !== "awaiting" && current.status !== status) {
      console.warn("pendingActions.resolve: status conflict", {
        id,
        currentStatus: current.status,
        requestedStatus: status,
      });
      return;
    }
    tx.update(ref, {
      status,
      resolvedAt: new Date().toISOString(),
      ...(opts.executionPreview ? { executionPreview: opts.executionPreview.slice(0, 500) } : {}),
    });
  });
}

// Stub returned to Claude in place of the real tool result. Claude reads
// this and generates a confirmation prompt for the family.
export function buildPendingActionStub(action: PendingAction): {
  _pending_action: true;
  actionId:        string;
  toolName:        string;
  preview:         string;
  expires_in_minutes: number;
  guidance:        string;
} {
  const minutes = Math.max(1, Math.ceil((new Date(action.expiresAt).getTime() - Date.now()) / 60_000));
  return {
    _pending_action: true,
    actionId:        action.id,
    toolName:        action.toolName,
    preview:         action.preview,
    expires_in_minutes: minutes,
    guidance:
      "This action is irreversible. Tell the family in plain English exactly what you are about to do, " +
      "then ask for an explicit YES before proceeding. Do NOT call this tool again until they confirm. " +
      "If they decline, acknowledge and stop. If they ask a question instead, answer it and re-ask for confirmation.",
  };
}
