import * as functions from "firebase-functions";
import * as admin from "firebase-admin";
import { sendViaInteractionAgent } from "../agents/caraAgent";
import { generateCaraMessage } from "../utils/caraMessage";

// Applications in these statuses count toward the job's applicantCount.
// "withdrawn" applications do NOT count.
const COUNTED_STATUSES = new Set(["pending", "accepted", "rejected"]);

function counts(status: string | undefined | null): boolean {
  return !!status && COUNTED_STATUSES.has(status);
}

/**
 * Maintains job_posts/{jobId}.applicantCount in response to writes on
 * job_applications/{appId}. Used by the Job Board "Less than 10 applicants"
 * badge.
 *
 * Create   → +1 (if status counts)
 * Delete   → -1 (if prior status counted)
 * Status change:
 *   counted → not-counted (e.g. withdrawn): -1
 *   not-counted → counted (re-applied): +1
 *   same bucket: no-op
 * jobId change: decrement old, increment new (rare/defensive)
 */
export const onJobApplicationWrite = functions.firestore
    .document("job_applications/{appId}")
    .onWrite(async (change, context) => {
        const before = change.before.exists ? change.before.data() : null;
        const after = change.after.exists ? change.after.data() : null;

        const beforeJobId: string | undefined = before?.jobId;
        const afterJobId: string | undefined = after?.jobId;
        const beforeStatus: string | undefined = before?.status;
        const afterStatus: string | undefined = after?.status;

        const beforeCounts = before ? counts(beforeStatus) : false;
        const afterCounts = after ? counts(afterStatus) : false;

        const deltas = new Map<string, number>();
        const bump = (jobId: string | undefined, delta: number) => {
            if (!jobId || delta === 0) return;
            deltas.set(jobId, (deltas.get(jobId) ?? 0) + delta);
        };

        if (beforeJobId && afterJobId && beforeJobId !== afterJobId) {
            // jobId changed — settle both sides
            if (beforeCounts) bump(beforeJobId, -1);
            if (afterCounts) bump(afterJobId, +1);
        } else {
            const jobId = afterJobId ?? beforeJobId;
            if (!beforeCounts && afterCounts) bump(jobId, +1);
            else if (beforeCounts && !afterCounts) bump(jobId, -1);
        }

        if (deltas.size === 0) return null;

        const db = admin.firestore();
        const ops: Promise<unknown>[] = [];
        for (const [jobId, delta] of deltas) {
            const ref = db.collection("job_posts").doc(jobId);
            ops.push(
                db.runTransaction(async (tx) => {
                    const snap = await tx.get(ref);
                    if (!snap.exists) return;
                    const current = (snap.data()?.applicantCount as number) ?? 0;
                    const next = Math.max(0, current + delta);
                    tx.update(ref, { applicantCount: next });
                }),
            );
        }

        try {
            await Promise.all(ops);
        } catch (err) {
            console.error("[onJobApplicationWrite] counter update failed", {
                appId: context.params.appId,
                deltas: Array.from(deltas.entries()),
                err,
            });
        }
        return null;
    });

/**
 * Notify the client when a caregiver applies to their job post. Fires once
 * per application (idempotency-guarded via `clientNotifiedAt` on the
 * application doc).
 *
 * Skips if the application was created in a "withdrawn" or "rejected" state
 * (e.g. backfill imports). Skips clients without active sessions or who are
 * opted out. The message is generated by Claude/gpt-4o-mini so it reads
 * naturally — no template-y blast.
 */
export const onJobApplicationCreated = functions.firestore
    .document("job_applications/{appId}")
    .onCreate(async (snap, context) => {
        try {
            const app = snap.data() ?? {};
            const status = app.status as string | undefined;
            if (status === "withdrawn" || status === "rejected") return;

            const jobId = app.jobId as string | undefined;
            if (!jobId) return;

            const db = admin.firestore();
            const jobSnap = await db.collection("job_posts").doc(jobId).get();
            if (!jobSnap.exists) return;
            const job = jobSnap.data() ?? {};

            const clientId = (job.clientId ?? job.userId ?? "") as string;
            if (!clientId) return;

            // Resolve client phone — agent_sessions is keyed by phone, indexed on userId
            const sessionQ = await db.collection("agent_sessions")
                .where("userId", "==", clientId)
                .limit(1)
                .get();
            if (sessionQ.empty) return;
            const sessionDoc  = sessionQ.docs[0];
            const sessionData = sessionDoc.data();
            if (sessionData.optedOut) return;
            if (sessionData.onboardingStep !== "complete") return; // don't interrupt onboarding
            const phone = (sessionData.phone ?? sessionDoc.id) as string;

            // Resolve caregiver display name (best effort)
            const cgId = (app.caregiverId ?? "") as string;
            let cgFirstName = "A caregiver";
            if (cgId) {
                const cgSnap = await db.collection("caregivers").doc(cgId).get();
                cgFirstName = ((cgSnap.data()?.name ?? "Caregiver") as string).split(" ")[0] || "Caregiver";
            }

            const seniorName = (job.seniorName ?? sessionData.onboardingData?.seniorName ?? "") as string;
            const jobTitle   = (job.title ?? "your care job") as string;
            const rate       = app.proposedRate as number | undefined;
            const rateLine   = typeof rate === "number" ? ` at $${rate}/hr` : "";
            const seniorPart = seniorName ? ` for ${seniorName}` : "";

            const message = await generateCaraMessage({
                audience: "family",
                context:
                    `Tell the family that ${cgFirstName} just applied to their job post${seniorPart}${rateLine}. ` +
                    `Keep it warm, one-to-two sentences. Offer to pull up the caregiver's profile — don't dump details. ` +
                    `End with a soft invitation like "Want me to share their profile?" or "Want to set up an intro call?"`,
                fallback:
                    `${cgFirstName} just applied to ${jobTitle}${rateLine}${seniorPart ? "" : ""}. Want me to pull up their profile?`,
                maxTokens: 100,
            });

            await sendViaInteractionAgent(phone, {
                content:     message,
                urgency:     "standard",
                sourceAgent: "job_applicant_alert",
                canDrop:     true,
            });

            await snap.ref.update({ clientNotifiedAt: new Date().toISOString() }).catch(() => {});
        } catch (err) {
            console.error("[onJobApplicationCreated] notify failed", { appId: context.params.appId, err });
        }
    });
